Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 150

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'

